export const UPDATE_QUESTION = "UPDATE_QUESTION";
export const ADD_QUESTION = "ADD_QUESTION";
export const UPDATE_SEARCH_QUESTION = "UPDATE_SEARCH_QUESTION";
export const SHOW_HOME_PAGE = "SHOW_HOME_PAGE";
export const SHOW_ADD_BUTTON = "SHOW_ADD_BUTTON";
